##############################################################################
# CISCO CONFIGURATION DATA
[cisco]

host_name = "R2"
user_name = "bersen"
pass_word = "bersen"


###############################################################################
# HTTP server configuration

[http]

http_addr = ":3000"

[https]

https_addr = ":443"
###############################################################################

